### ISSUE TITLE
Issue downloading WikiHow

### ISSUE THREAD

**Issue by jpilaul** [YiSyuanChen/MTL-ABS#3]
Hi Yi-Syuan,
Thank you so much for releasing the code for your paper. I am trying to download WikiHow using:

```
python prepro/prepro_tfds_dataset.py -mode download -dataset wikihow -output_path ../datasets/organized_raw_datasets/ -art_feature_name text -summ_feature_name headline
```

And got the following error:

> Downloading and preparing dataset 5.21 MiB (download: 5.21 MiB, generated: Unknown size, total: 5.21 MiB) to /home/ubuntu/tensorflow_datasets/wikihow/all/1.2.0...
Dl Size...: 0 MiB [00:00, ? MiB/s]rl/s]
Dl Completed...: 0 url [00:00, ? url/s]
Traceback (most recent call last):
  File "prepro/prepro_tfds_dataset.py", line 103, in <module>
    dataset.download_and_prepare()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 441, in download_and_prepare
    download_config=download_config,
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1134, in _download_and_prepare
    dl_manager, **optional_pipeline_kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorflow_datasets/summarization/wikihow.py", line 135, in _split_generators
    os.path.join(dl_manager.manual_dir,
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 149, in __get__
    cached = self.fget(obj)  # pytype: disable=attribute-error
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 655, in manual_dir
    f'Manual directory {self._manual_dir} does not exist or is empty. '
AssertionError: Manual directory /home/ubuntu/tensorflow_datasets/downloads/manual does not exist or is empty. Create it and download/extract dataset artifacts in there using instructions:
Links to files can be found on https://github.com/mahnazkoupaee/WikiHow-Dataset
Please download both wikihowAll.csv and wikihowSep.csv.

I was wondering if you had a quick fix (otherwise I can do it manually).

Thanks!

**Comment by jpilaul** [comment]
ah nevermind... just read that I need to download it manually from here https://www.tensorflow.org/datasets/catalog/wikihow
sorry about that!
